config/routes.rb
Rails.application.routes.draw do
  root "homepage#show"

  namespace :api do
    namespace :v1, defaults: {format: :json} do
      patch "/links/mark-as-read", to: "links#update"
      get "/links/sort-alphabetically", to: "links#index"
    end
  end

  resources :users, only: [:new, :create]
  resources :links, only: [:index, :create, :edit, :show, :update]

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  validates :url, presence: true
  validates :title, presence: true

  def change_read_status
    if self.read == "f"
      self.update_attribute("read", "t")
    else
      self.update_attribute("read", "f")
    end
  end

  def self.sort_alphabetically(user)
    where("user_id = #{user.id}")
    .order("links.title")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true
  validates :password, presence: true
  validates :email,    presence: true, uniqueness: true
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApplicationController
  def update
    @link = Link.find(params[:id])
    @link.change_read_status
    render json: @link
  end

  def index
    @links = Link.sort_alphabetically(current_user)
    render json: @links
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def show

  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @user = current_user
    @links = Link.where(user_id: current_user)
  end

  def create
    @link = Link.new(link_params)
    @link.user_id = current_user.id
    if @link.save
      flash[:success] = "Successfully created #{@link.title}"
      redirect_to links_path
    else
      flash.now[:warning] = @link.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @link = Link.find(params[:id])
    @user = current_user
  end

  def update
    link = Link.find(params[:id])
    if link.update(link_params)
      flash[:success] = "Your updates have been saved"
      redirect_to links_path
    else
      flash.now[:warning] = link.errors.full_messages.join(", ")
      render :edit
    end
  end

  private

    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session[:return_to] ||= request.referer
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to links_path
    else
      flash.now[:warning] = "Invalid email or password. Try Again."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Goodbye!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to links_path
    else
      flash.now[:warning] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :password, :email, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_status(status)
    status == "t" ? "true" : "false"
  end

  def truncate_link(link)
    limited_body = truncate(link, length: 20)
  end

  def check_status(status)
    status == "t" ? "read" : "unread"
  end

  def button(link)
    if link.read == "t"
      "Mark As Unread"
    else
      "Mark As Read"
    end
  end
end

app/views/homepage/show.html.erb
<div class="homepage">
    <h1>Urlockbox</h1>
    <%= link_to "Sign In", login_path, class:"btn button-indigo" %>
    <%= link_to "Sign Up", new_user_path, class:"btn button-gold" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Urlockbox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %> text-center alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <%= sanitize(message) %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/links/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid col-lg-12">
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-left">
        <li class="purple-text">Ur</li><li class= "blue-text"> Lockbox</li>
      <ul>
    </div>
    <div class="filter col-sm-offset-4">
      <label>Filter By Title: </label>
      <%= text_field :link, :filter_title %>
    </div>
    <div class="filter col-sm-offset-7">
      <label>Filter By Url: </label>
      <%= text_field :link, :filter_url %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if @current_user %>
        <li class="custom-nav"> Logged in as <%= user.username %> </li>
        <li><%= link_to "Sign Out", logout_path, method: :delete %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/links/edit.html.erb
<%= render partial: 'navbar', locals: {user: @user} %>

<div class="circle-list col-sm-offset-3 offest">
  <%= form_for @link do |f| %>
    <div class="form-group username">
      <%= f.label :title %>
      <br>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <br>
    <div class="form-group email">
      <%= f.label :url %>
      <br>
      <%= f.url_field :url, class: "form-control" %>
    </div>

    <%= f.submit "Update Link", class: "btn button-gold" %>
  <% end %>
<div>

app/views/links/index.html.erb
<%= render partial: 'navbar', locals: {user: @user} %>

<div class="circle col-md-offset-1">
  <div class="create-link">
    <%= form_for Link.new do |f| %>
    <div class="form-group username">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group email">
      <%= f.label :url %>
      <%= f.url_field :url, class: "form-control" %>
    </div>

    <%= f.submit "Create Link", class: "btn button-indigo" %>
    <% end %>
  </div>
</div>

<div class="title">Ur <a class="title2">Ls</a></div>
<div class="circle-list col-sm-offset-5">
  <button class="read1 btn btn-xs">Read</button>
  <button class="unread btn btn-xs">Unread</button>
  <button class="all btn btn-xs">View All</button>
  <button class="alphabetical btn btn-xs">Alphabetical</button>
  <table>
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Url</th>
        <th>Read</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @links.each do |link| %>
        <tr class="tr_<%= link.id %>" id="<%= check_status(link.read) %>" data-title="<%= link.title %>" data-url="<%= link.url %>">
          <td>
            <button class="read btn button-indigo btn-xs" id="btn_<%= link.id %>"data-id="<%= link.id %>"> <%= button(link) %> </button>
          </td>
          <td><%= link.title %></td>
          <td><%= truncate_link(link.url) %></td>
          <td class="read_<%= link.id %>"><%= render_status(link.read) %></td>
          <td>
            <%= button_to "Edit", edit_link_path(link), method: :get, class: "btn button-gold btn-xs" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="homepage">
  <div class="panel-body col-md-4 col-md-offset-4">
    <%= form_for @user do |f| %>
    <div class="form-group username">
      <%= f.label :username %>
      <%= f.text_field :username, class: "form-control" %>
    </div>

    <div class="form-group email">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group password">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </div>

    <div class="form-group password2">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <%= f.submit "Sign Up", class: "btn button-indigo" %>
    <% end %>
  </div>
</div>